### PR TITLE
Final change log update for v3.0.1 model

### PR DESCRIPTION
**Pull request by bact**
This PR will be merge when we are happy to freeze the 3.0.1 and make tag release of the 3.0.1 model.

- [x] Remove "Unrelease" note from 3.0.1 heading
- [x] Grouped same type of changes together
- [ ] Update the date in the change log to the date of latest changes before freezing 3.0.1.
- To be logged
  - [x] #908
  - [x] #913

See change log update for the spec at https://github.com/spdx/spdx-spec/pull/1123

### CODE REVIEW

**Comment by zvr** [comment]
Converting to "draft" to prevent accidental merging, since the 3.0.1 will happen when we get the OMG feedback and incorporate whatever changes come up.

**Review by kestewart — APPROVED** [review]

**Comment by bact** [comment]
(Mark as draft again to prevent merge until we decide to freeze. Was undrafted previously to merge changes from main.)

**Comment by kestewart** [comment]
@bact - when will you feel comfortable moving this out of draft?   I think we're getting ready to tag 3.0.1; and it would be good for this to be part of it.

**Comment by bact** [comment]
@kestewart  I think it's ready.  Just recently logged #908 and #913

**Review by zvr — APPROVED** [review]

**Pull request merged**
