### PR TITLE
Update energyConsumption.md

### PR DESCRIPTION
**Pull request by rgopikrishnan91**
@kestewart @goneall Please review this PR. Modified per our call. Part 2 of the PR

### CODE REVIEW

**Comment by goneall** [comment]
@rgopikrishnan91 We need to include a class definition for `EnergyConsumption` similar to `AIPackage` with the properties defined as discussed in the call.

**Comment by goneall** [comment]
@rgopikrishnan91 - I just noticed the other PR's - can you combine these into a single PR that can be reviewed together?

**Review by kestewart — APPROVED** [review]
This one looks fine.   Please merge with other PRs & add "Signed off By"

**Comment by rgopikrishnan91** [comment]
Closing the PR as its moved to #697

**Pull request closed without merging**
