### PR TITLE
AI Profile: Use singular for properties

### PR DESCRIPTION
**Pull request by armintaenzertng**
According to #226, property names should be kept singular. I changed this for the AI profile.

`modelDataPreprocessingSteps` and `modelExplainabilityMechanisms` made this approach slightly awkward, as they both have `maxCount = 1` but can list multiple "values" (see also #227). I have a proposal to circumvent this issue by removing the "Steps" and "Mechanisms", respectively. Feel free to disagree.

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM - Thanks @armintaenzertng

**Comment by kestewart** [comment]
@rgopikrishnan91 - please comment.  I'm concerned this is significantly changing the semantics.

**Comment by rgopikrishnan91** [comment]
I think data preprocessing in particular can be multiple steps, we need that property element to be able to represent and denote that. For instance, the data can first have outliers removed, normalized and then embedded. So even though it can be written in one line of text, these are three distinct steps.

**Comment by goneall** [comment]
@rgopikrishnan91 Could we have each step be a separate string and remove the maxCount?

**Comment by maxhbr** [comment]
> I think data preprocessing in particular can be multiple steps, we need that property element to be able to represent and denote that. For instance, the data can first have outliers removed, normalized and then embedded. So even though it can be written in one line of text, these are three distinct steps.

I think this could be a follow-up PR.

**Comment by maxhbr** [comment]
@armintaenzertng : I rebased this PR

**Review by maxhbr — APPROVED** [review]
LGTM

**Comment by rgopikrishnan91** [comment]
@goneall I think I am okay with it being multiple strings and each step (or any two logically) being in different strings. Same for the model explainability mechanism

**Comment by rgopikrishnan91** [comment]
@kestewart what do you think?

**Pull request merged**
