### PR TITLE
Remove dataLicense from CreationInfo

### PR DESCRIPTION
**Pull request by goneall**
Resolves issue #341

### CODE REVIEW

**Comment by zvr** [comment]
Although I voted for this, we should wait for the resolution of https://github.com/spdx/change-proposal/issues/8 before merging it.

**Comment by goneall** [comment]
> Although I voted for this, we should wait for the resolution of [spdx/change-proposal#8](https://github.com/spdx/change-proposal/issues/8) before merging it.

Agree - I'll change this to draft.

Here's next steps copied from the meeting etherpad where this was discussed:

```
* Steve to upload minutes to meetings repo
* Steve to send details of current discussion and considered options to the mailing lists
* Jilayne to contact EU legal list for their input
* Timing: next release of SPDX spec will be in a week and a half, ideally would have this solution incorporated by then
```

@jlovejoy @swinslow - if you could update this issue once the decision is finalized.

**Review by maxhbr — APPROVED** [review]
The changes look fine.

**Comment by swinslow** [comment]
Thanks all. As mentioned in #341, consensus was not reached at the 2023-07-27 meeting about whether to (1) keep the field but broaden it to permit using any valid license expression, or (2) remove the field altogether. Links to the discussion and details are in #341.

**Comment by maxhbr** [comment]
@swinslow : any updates here, was there further discussion?

**Comment by davaya** [comment]
PR #500 includes physical document level support for dataLicense.

**Review by zvr — APPROVED** [review]

**Review by swinslow — APPROVED** [review]
+1 to remove dataLicense from CreationInfo, will follow up in change proposal thread regarding inclusion as an optional field in SpdxDocument

**Pull request merged**
