### PR TITLE
Add .editorconfig and .gitattributes to enforce newline and whitespace consistency

### PR DESCRIPTION
**Pull request by bact**
Copying configurations from `spdx/spdx-spec` repo (sorted):

- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/.editorconfig
- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/.gitattributes

### CODE REVIEW

**Comment by zvr** [comment]
Why shouldn't people in Windows have their native line endings?

Sorry, I may be misunderstanding something...

**Comment by bact** [comment]
We can make it auto (`crlf` for Windows, `lf` for the rest), just try keeping both `spdx-spec` and `spdx-3-model` repos using the same convention.

**Review by goneall — APPROVED** [review]
LGTM

**Review by kestewart — APPROVED** [review]
This is a very good idea.   Thank you!

**Pull request merged**
