### PR TITLE
Updated model diagrams for changes 02-15-24 to 04-11-24

### PR DESCRIPTION
**Pull request by sbarnum**
This includes all changes in the diff for 02-15-24 to 04-08-24.

The diagram set aligns to the submission to OMG for ISO fast track.
This includes breaking out Core, Core Enumerations, Software, and Software Enumerations diagrams in addition to the preexisting combined Core+Software diagram.
It also includes both .png (for easy and portable web and document inclusion) and .svg (for cleanly scalable use)versions of each document.

### CODE REVIEW

**Comment by kestewart** [comment]
@bact - can you take a review pass, as you've been involved in most of the recent AI / Dataset changes.

**Comment by bact** [comment]
These new classes, properties, and enums from #697 are not in the diagram yet:
- model/AI/Classes/EnergyConsumption
- model/AI/Classes/EnergyConsumptionDescription
- model/AI/Properties/energyQuantity
- model/AI/Properties/energyUnit
- model/AI/Properties/finetuningEnergyConsumption
- model/AI/Properties/inferenceEnergyConsumption
- model/AI/Properties/trainingEnergyConsumption
- model/AI/Vocabularies/EnergyUnitType

This will get updated by #706:
- model/AI/Properties/energyConsumption

**Comment by bact** [comment]
Two different kinds of reference to `PresenceType`:
- In the `AIPackage`, the label is `PresenceType`.
  - as used in `useSensitivePersonalInformation` and `autonomyType`
- In the `DatasetPackage`, the label is `Core/Vocabularies/PresenceType`.
  - as used in `hasSensitivePersonalInformation`.

I'm not sure which convention we should use.
This may related to #707 as well.

**Comment by bact** [comment]
The merged #698 updated new IRIs but IRIs of `NoAssertionLicense` and `NoneLicense` that shown in Licensing model diagram still use the old IRIs.

I have open a separated PR #712 to fix this.

**Comment by bact** [comment]
**These are all post-8 April 2024.**

In `AIPackage`, the `energyConsumption` type is now changed to `EnergyConsumption`. This will get updated by PR #706.

--

These new classes, properties, and enums from #697 (merged on 8 or 9 Apr) for AI Profile are not in the diagram yet:
- model/AI/Classes/EnergyConsumption
- model/AI/Classes/EnergyConsumptionDescription
- model/AI/Properties/energyQuantity
- model/AI/Properties/energyUnit
- model/AI/Properties/finetuningEnergyConsumption
- model/AI/Properties/inferenceEnergyConsumption
- model/AI/Properties/trainingEnergyConsumption
- model/AI/Vocabularies/EnergyUnitType

**Comment by kestewart** [comment]
@sbarnum - please see the changes that @bact has been making for the late AI changes, and see if you can incorporate so we don't get a merge conflict.

**Comment by bact** [comment]
model Core Enumerations:

--

in RelationshipType, Pedigree section:

- `expandsTo`, does not have types (should be `[artifact->element]` ?)
- `packages`, in the Pedigree section, is annotated with `(obsolete?)` - do we need an update here?

--

in ExternalIdentifierType:

- `cpe_2.2` -> `cpe22`
- `cpe_2.3` -> `cpe23`
- `crystalKyber` -> `crystalsKyber`

This should get fixed by PR  #714.

--

**Comment by sbarnum** [comment]
> The merged PR https://github.com/spdx/spdx-3-model/pull/698 (7 or 8 Apr) updated new IRIs but IRIs of NoAssertionLicense and NoneLicense that shown in Licensing model diagram still use the old IRIs.

> https://rdf.spdx.org/v3/ExpandedLicensing/NoAssertionLicense -> https://spdx.org/rdf/3.0.0/terms/Licensing/NoAssertion
> https://rdf.spdx.org/v3/ExpandedLicensing/NoneLicense -> https://spdx.org/rdf/3.0.0/terms/Licensing/None

This will be fixed in the final update PR

**Comment by sbarnum** [comment]
> The diagrams for `AIPackage` and `DatasetPackage` used two different kinds of reference to `PresenceType`:
> 
> * In the `AIPackage` diagram, the label is `PresenceType`.
>   
>   * as used in `useSensitivePersonalInformation` and `autonomyType`
> * In the `DatasetPackage` diagram, the label is `Core/Vocabularies/PresenceType`.
>   
>   * as used in `hasSensitivePersonalInformation`.
> 
> In [`AIPackage.md`](https://github.com/spdx/spdx-3-model/blob/main/model/AI/Classes/AIPackage.md) and [`DatasetPackage.md`](https://github.com/spdx/spdx-3-model/blob/main/model/Dataset/Classes/DatasetPackage.md) they are all `type: /Core/PresenceType`.
> 
> I'm not sure which convention we should follow. @rgopikrishnan91 @bennetkl do you have an idea please?
> 
> This may related to #707 as well.

This will be fixed in the finalupdate PR.
They will all be "/Core/PresenceType"

**Comment by sbarnum** [comment]
> model Core Enumerations:
> 
> --
> 
> in RelationshipType, Pedigree section:
> 
> * `expandsTo`, does not have types (should be `[artifact->element]` ?)
> * `packages`, in the Pedigree section, is annotated with `(obsolete?)` - do we need an update here?
> 
> --
> 
> in ExternalIdentifierType:
> 
> * `cpe_2.2` -> `cpe22`
> * `cpe_2.3` -> `cpe23`
> * `crystalKyber` -> `crystalsKyber` (typo)
> 
> This should get fixed by PR #714.
> 
> --

cpe22 & cpe23 will be fixed in the final update PR.

'expandsTo' will change to include [artifact->artifact] to align with its definition in the md file ("expandsTo: The from archive expands out as an artifact described by each to Element")

'packages' will be removed as it is not present in RelationshipType.md and looks to be obsolete.

I am making no change for 'crystalKyber' as I see no such entry in ExternalIdentifierType and am unsure what this comment is intended to mean.

**Comment by bact** [comment]
@sbarnum I'm sorry, the `crystalKyber` -> `crystalsKyber` is from `HashAlgorithm`.

[model/Core/Vocabularies/HashAlgorithm.md](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/HashAlgorithm.md)

**Comment by sbarnum** [comment]
> @sbarnum I'm sorry, the `crystalKyber` -> `crystalsKyber` is from `HashAlgorithm`.
> 
> It's a typo. "s" is missing.
> 
> [model/Core/Vocabularies/HashAlgorithm.md](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/HashAlgorithm.md)
> 
> (i have edited the previous comment accordingly)

Got it.
The change will be included

**Comment by kestewart** [comment]
@sbarnum - can you resolve the model.drawio conflicting file issue?

**Comment by sbarnum** [comment]
This PR should now include the above described fixes to the helpful comments from @bact as well as updates for all the changes in the diff file from 04-08-24 to 04-11-24.

I will note that the diff file was missing some changes (it included the change in type for the energyConsumption property on AIPackage but did not include the new EnergyConsumption and EnergyConsumptionDescription classes, their properties, or the new EnergyUnitType vocabulary).

The fact that there were clearly some items missing from the diff does not give me 100% confidence that the diagrams are completely correct.
They should be correct to the baseline, the comments from @bact above, the diff, and a few things I noticed and fixed but I could easily not notice something that the diff failed to include.

**Comment by bact** [comment]
Thank you @sbarnum

**Comment by sbarnum** [comment]
> @sbarnum - can you resolve the model.drawio conflicting file issue?

Done

**Review by kestewart — APPROVED** [review]

**Comment by kestewart** [comment]
Thank you @sbarnum - given that @bact has +1'd them, and I took a pass and am not spotting anything weird.   If we can get either @rnjudge or @goneall to add their review, we'll merge them and consider them baseline.   Further fixes can be applied ontop of them.

**Review by rnjudge — APPROVED** [review]

**Comment by rnjudge** [comment]
@sbarnum can you resolve the merge conflicts then I can merge?

**Review by bact — APPROVED** [review]

**Pull request merged**
