### PR TITLE
[Diagram] Remove all named individuals

### PR DESCRIPTION
**Pull request by bact**
- <s>#880 added SpdxOrganization as a named individual to the model
- This PR updates the diagrams to reflect that change
- See also the change log at #881</s>

Per Tech Call 24 Sep 2024 - Remove all named individuals to "fix" IRI inconsistencies between the model and the diagram.

Removing:
- Core/NoAssertionElement
- Core/NoneElement
- Licensing/NoAssertionLicense
- Licensing/NoneLicense

### CODE REVIEW

**Comment by bact** [comment]
@sbarnum Since this is about diagram, if you have few mins please take a look at the SpdxOrganization individual added.

It is in the "Individuals" box in two diagrams:
- Core: the box is at the bottom-right corner
- Core+Software: the box is near the top-right corner

Thank you for your help.

**Comment by sbarnum** [comment]
I see two problems, none of which are directly caused by the diagram changes but rather by the changes to SPDXOrganization that led to the diagram changes.

1. The currently defined IRI for SPDXOrganization is inconsistent with other IRIs for named individuals. As a named Individual, the IRI identifier for the SPDXOrganization should at least be "https://spdx.org/rdf/SPDXOrganization". It is currently missing the "rdf" portion which aligns to all of the other named Individuals. It is fine leaving out the release version portion of the IRI path as this individual spans versions but it should at least have the rdf portion. To be even more consistent it should actually probably be "https://spdx.org/rdf/Core/SPDXOrganization" given that it is defined as part of Core.
2. In the SPDXOrganization.md file, under metadata it lists only the IRI prefix under "IRI". This metadata field should assert the full IRI (as specified above) for the named individual. This is something I have long suggested should be done for all named individuals. 

These issues should be addressed then updated in the diagrams.

BTW, there is also a remaining typo in buildType.md. There is an occurence of "builtType" rather than "buildType"

**Comment by bact** [comment]
Thank you @sbarnum for the typos, please see PR #885

**Comment by goneall** [comment]
> The currently defined IRI for SPDXOrganization is inconsistent with other IRIs for named individuals. As a named Individual, the IRI identifier for the SPDXOrganization should at least be "https://spdx.org/rdf/SPDXOrganization". It is currently missing the "rdf" portion which aligns to all of the other named Individuals. It is fine leaving out the release version portion of the IRI path as this individual spans versions but it should at least have the rdf portion. To be even more consistent it should actually probably be "https://spdx.org/rdf/Core/SPDXOrganization" given that it is defined as part of Core.

@sbarnum see different but related discussion at https://github.com/spdx/spdx-3-model/pull/880#issuecomment-2346408352

@zvr - thoughts?  I'm OK with either URI

**Comment by bact** [comment]
fyi, these are named individuals we currently have, together with their IRIs:

1. [SpdxOrganization](https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Individuals/SpdxOrganization/)
    - Standard IRI: https://spdx.org/rdf/3.0.1/terms/Core/SpdxOrganization
    - Custom IRI: https://spdx.org/ (defined in Markdown file as generated into owl:sameAs)
1. [NoAssertionElement](https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Individuals/NoAssertionElement/)
    - Standard IRI: https://spdx.org/rdf/3.0.1/terms/Core/NoAssertionElement
    - Custom IRI: https://spdx.org/rdf/3.0.1/terms/Core/NoAssertion (displayed in spec diagrams, but not actually defined in Markdown file and thus not generated into the RDF)
1. [NoneElement](https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Individuals/NoneElement/)
    - Standard IRI: https://spdx.org/rdf/3.0.1/terms/Core/NoneElement 
    - Custom IRI: https://spdx.org/rdf/3.0.1/terms/Core/None (displayed in spec diagrams, but not actually defined in Markdown file and thus not generated into the RDF)
1. [NoAssertionLicense](https://spdx.github.io/spdx-spec/v3.0.1/model/ExpandedLicensing/Individuals/NoAssertionLicense/)
    - Standard IRI: https://spdx.org/rdf/3.0.1/terms/ExpandedLicensing/NoAssertionLicense
    - Custom IRI: https://spdx.org/rdf/3.0.1/terms/Licensing/NoAssertion (both defined in Markdown and displayed in spec diagram)
1. [NoneLicense](https://spdx.github.io/spdx-spec/v3.0.1/model/ExpandedLicensing/Individuals/NoneLicense/)
    - Standard IRI: https://spdx.org/rdf/3.0.1/terms/ExpandedLicensing/NoneLicense
    - Custom IRI: https://spdx.org/rdf/3.0.1/terms/Licensing/None (both defined in Markdown and displayed in spec diagram)

(#883 is proposed to fix inconsistencies in (2) and (3))

**Comment by zvr** [comment]
Thinking more about it, I am not even sure the Individuals should appear on the diagram...

I mean, we will also publish hundreds more Individuals -- the licenses and exceptions of the License List. Why show some and not all?

**Comment by goneall** [comment]
based on the tech call on 24 Sept 2024: We'll remove the individuals from the diagram - SpdxOrganization, NoneElement, NoAssertionElement, NoneLicense, NoAssertionLicense.  Resolves the inconsistencies' and allows us to move the decision on the URI's to 3.1.

**Comment by goneall** [comment]
@bact will update the diagram based on the above decision

**Comment by bact** [comment]
All named individuals are now removed from the diagrams.

**Comment by goneall** [comment]
Thanks @bact

**Review by goneall — APPROVED** [review]
LGTM

**Comment by goneall** [comment]
@sbarnum @zvr - Please review and if it looks good, let's merge - we want to freeze the changes for the ISO submittal.  It would be nice to have the diagram consistent with the model.

**Review by bobmartin3000 — APPROVED** [review]
LGTM

**Review by zvr — APPROVED** [review]

**Pull request merged**
