### PR TITLE
Add payloads to use cases

### PR DESCRIPTION
**Pull request by davaya**
Add serialized payloads containing multiple elements to use case list

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM - although it would be a bit more work for the examples - BTW - @armintaenzertng did some of this in his recent JSON-LD examples

**Comment by goneall** [comment]
@davaya - can you resolve the merge conflicts?

@maxhbr  - if you agree / approve I can merge once the conflicts are resolved

**Review by goneall — APPROVED** [review]
Looks like some good additions

**Comment by goneall** [comment]
@zvr @JPEWdev @maxhbr - If any of you could review and if you agree with the PR, I can merge this in for 3.0

**Comment by maxhbr** [comment]
This has conflicts -> can not be reviewed.

And it is fairly stale and https://github.com/spdx/spdx-3-serialization-prototype-playground/tree/main/jsonld should basically replace / rewrite the serialization content here.

**Comment by goneall** [comment]
> This has conflicts -> can not be reviewed.
> 
> And it is fairly stale and https://github.com/spdx/spdx-3-serialization-prototype-playground/tree/main/jsonld should basically replace / rewrite the serialization content here.

Thanks @maxhbr for taking a look.  I'll go ahead and close this PR as stale.

**Pull request closed without merging**
