### PR TITLE
[3.0] AI: Update safetyRiskAssessment property desc to refer to general risk assessment

### PR DESCRIPTION
**Pull request by bact**
Change description text for risk categories to refer to EU General Risk Assessment Methodology, not EU AI Act - as agreed in SPDX AI Team Meeting 2024-03-20.

See more analysis and discussions in #650.

### CODE REVIEW

**Review by kestewart — APPROVED** [review]
Thanks for the updates.  This is clearer now.

**Review by bennetkl — APPROVED** [review]
The change looks good,  I might have called AI systems instead of AI software, but they are basically the same thing.

**Comment by bact** [comment]
@bennetkl I can replace every instances on "AI software" to "AI system" here if you like.

**Comment by bact** [comment]
Updated to "AI system" per @bennetkl  comment.

**Review by kestewart — APPROVED** [review]

**Comment by rgopikrishnan91** [comment]
Overall looks good to me. Just wondering "is intended to assist authorities when they assess general product safety compliance.
" if this wording should be "is intended to help AI system creators/maintainers to declare the results of safety risk assessment and assist authorities when they assess/record general product safety compliance."

@kestewart

**Comment by bact** [comment]
> Overall looks good to me. Just wondering "is intended to assist authorities when they assess general product safety compliance. " if this wording should be "is intended to help AI system creators/maintainers to declare the results of safety risk assessment and assist authorities when they assess/record general product safety compliance."

Very good point. I basically copied the text from the EU General Risk Assessment Methodology. As they are the document from the "authority" side, it is understandable to see it written from that perspective. We can adjust.

**Comment by bact** [comment]
Btw, the current paragraph is:

"Using categorization according to the EU general risk assessment methodology which implements Article 20 of Regulation (EC) No 765/2008 and is intended to assist authorities when they assess general product safety compliance."

The "is intended..." part is to describe the assessment methodology and not to directly describe the property itself. The sentence is probably too long. I have break them into two sentences to make it more explicit that "is intended" is describing the methodology.

I have also put your suggestion on "to declare the results of safety risk assessment" to the summary and the first line of description - without directly mentioning AI creator/maintainer, assuming that it is already creator/maintainer who creating SBOM.

@rgopikrishnan91 please PR #683 for updates

**Pull request merged**
