### PR TITLE
AI: Update safetyRiskAssessment description

### PR DESCRIPTION
**Pull request by bact**
Update to make it more explicit about the intention of the property and the intention of the assessment methodology.
- Rewrite the second paragraph of the description so the word "is intended" is clearly refer to the methodology, and not the property.
- The property is intended to "Records the results of general safety risk assessment of the AI system."
- The methodology (which we borrowed in) is intended to "assist authorities when they assess general product safety compliance."

See comment/suggestion by @rgopikrishnan91 and discussion in https://github.com/spdx/spdx-3-model/pull/675#issuecomment-2023787199

### CODE REVIEW

**Comment by bact** [comment]
@bennetkl please kindly review

**Comment by bennetkl** [comment]
Reviewed / approved.  Further discussions in 3.1 might be needed but we can open a new PR.

**Review by bennetkl — APPROVED** [review]
Reviewed and approved

**Comment by rgopikrishnan91** [comment]
LGTM

**Review by kestewart — APPROVED** [review]
Thanks for these changes.  Read's better.

**Pull request merged**
