### PR TITLE
Create Support Level to associate different types of support with an artifact. 

### PR DESCRIPTION
**Pull request by kestewart**
The support available for a software artifact is a factor increasingly being used in risk assessment.  equirement of listing the support type available.   This set of enumerations has been based on the enumerations in ["Managing Legacy Technology Security (HIC-MaLTS)" from the Healthcare & Public Health Sector Coordinating Councils](https://healthsectorcouncil.org/wp-content/uploads/2023/03/Health-Industry-Cybersecurity-Managing-Legacy-Technology-Security-HIC-MaLTS.pdf), with additional categories being added after discussion with the AI & Data profile working groups.   It can be applied to software components, AI/ML trained models and datasets; in the medical industry as well as other industries. 

Signed-off-by: Kate Stewart <kstewart@linuxfoundation.org>

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM

**Review by bennetkl — APPROVED** [review]
The SPX-AI WG discussion talked about also adding No Assertion, which I see you have done, because currently at least with AI/Dataset, none of these artifacts have any kind of support.  We probably should add an example of limited support ie.  is that limited to specific times of day?  type of issues?  or something else.

Approved to merge into main

**Review by maxhbr — APPROVED** [review]
LGTM

**Comment by kestewart** [comment]
Thanks @bennetkl, @goneall, @maxhbr for the quick turn on the reviews!   Merging this now.

**Pull request merged**
