### PR TITLE
Add individual element class to core diagram

### PR DESCRIPTION
**Pull request by sbarnum**
This PR is for two very simple changes to the diagrams.
The new IndividualElement subclass of Element is added to the Core diagram in the .drawio diagrams file.
The Core diagram is exported to generate an updated model-Core.png raster image of the Core diagram.

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM - matches discussion on tech call

**Review by bact — APPROVED** [review]

**Comment by goneall** [comment]
@zvr - could you review / merge?  Hopefully this still fits in the ISO submission timeframe.

**Review by zvr — APPROVED** [review]

**Comment by zvr** [comment]
The PNG has to also go to the spec repo.

**Comment by goneall** [comment]
> The PNG has to also go to the spec repo.

I just created https://github.com/spdx/spdx-spec/pull/1161

**Pull request merged**
