### PR TITLE
Create metrics.md

### PR DESCRIPTION
**Pull request by rgopikrishnan91**
create a properties file for metrics @zvr @kestewart @lumjjb

### CODE REVIEW

**Review by kestewart — CHANGES_REQUESTED** [review]
Summary:  remove redundant spacing after "This "
Description:  are there references to a standard set of metrics that should be referenced?

**Review by bennetkl — APPROVED** [review]
Remove extra space in Title.  This is not a blocker.

**Comment by rgopikrishnan91** [comment]
Hi @kestewart , For the description, there is currently only a glossary of ML terms that are being worked on in IEEE. But there is no comprehensive standard as of now that describes all possible ML evaluation metrics AFAIK

**Review by kestewart — APPROVED** [review]

**Comment by kestewart** [comment]
Given no taxonomy agreed on yet,  let's keep it as is for now, and refine in future.

**Pull request merged**
