### PR TITLE
Fix typos: hasPrerequsite -> hasPrerequisite, and others

### PR DESCRIPTION
**Pull request by bact**
- Fix typo in hasAddedFile: "is is" -> "is"
- Fix typo in type name: "hasPrerequsite" -> "hasPrerequisite"
- Make fullstops and commas in of all types in RelationshipType consistent.
  - some "during a LifecycleScopeType period" have comman before it, some don't
  - some description with one sentence have fullstop, some don't

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM

**Comment by bact** [comment]
@goneall I have pushed another commit after your approval to fix: hasPrerequsite -> hasPrerequisite.

There's a typo of this hasPrerequisite relationship type as well in the 2.3->3.0 translation table. I will open another PR to fix that together with the strikethrough formatting.

**Review by goneall — APPROVED** [review]
Good catch @bact 

This could be a breaking change if anyone is using the incorrectly spelled 3.0.0 version.

That being said, I believe we should go ahead and merge this in now so we don't propagate the miss-spelled property further.

@zvr @kestewart - agree?

**Comment by bact** [comment]
> This could be a breaking change if anyone is using the incorrectly spelled 3.0.0 version.
> 
> That being said, I believe we should go ahead and merge this in now so we don't propagate the miss-spelled property further.

For anyone using 3.0.0, it will still be the same name with typo, as this PR will apply only to 3.0.1 (and we have separate IRIs for the two). Unless we like to retrospectively change this in 3.0.0 as well.

I think if it is a human author, they may spot the typo and corrected it by themselves (so lesser degree of an issue?). But if it's a machine or machine-assisted, very likely that it will just follow the mis-spelled information in the schema file (which is considered correct).

The Dots tool, for example, is unfortunately affected by this typo:

Screenshot 2024-07-31 at 20 08 10

**Comment by bact** [comment]
For "hasPrerequsite" -> "hasPrerequisite",
if needed, we can also put an errata like one in [2.3.1](https://github.com/spdx/spdx-spec/blob/2326abefbdeb20b995fb9feab8e1a8f6542bf8dd/chapters/package-information.md#7241-description):

> Cardinality 	0..1
NOTE: The cardinality was incorrectly printed as 0..* in the original publishing of the 2.3 specification

**Review by zvr — APPROVED** [review]

**Pull request merged**
