### PR TITLE
Doc: Diagram: Fix typo in DatasetPackage; Fix arrow label positions in Licensing; Sort properties

### PR DESCRIPTION
**Pull request by bact**
- Fix typo in DatasetPackage: `datasetPreprocessing` -> `dataPreprocessing`
- Fix arrow label positions in Licensing (`*` and `2..*` between `AnyLicenseInfo`, `ConjuctiveLicenseSet`, and `DisjunctiveLicenseSet`)
- Sort in Diagram: properties/enums in AI, Dataset, Software Enumerations, and Licensing to match order in the spec https://spdx.github.io/spdx-spec/v3.0/
- Sort in related Markdown files
- Fix Markdown format warnings (markdownlint)

### CODE REVIEW

**Comment by bact** [comment]
@sbarnum please kindly review

**Review by goneall — APPROVED** [review]
LGTM

**Comment by zvr** [comment]
Argh!  Splitting vocabularies to multiple lines stops the whole parsing. @bact

**Comment by zvr** [comment]
It makes no sense to have PRs doing a number of unrelated changes...

**Comment by bact** [comment]
Thank you @zvr. Sorry for the break. I'm fixing this now.

**Comment by bact** [comment]
@zvr can you check this https://github.com/spdx/spec-parser/pull/129 ? 

If this solution is ok, I will implement a similar thing for NestedListSection as well. Thank you.

**Comment by zvr** [comment]
Let's fix the input.

I can provide a PR in the weekend, if noone else does before then.

**Pull request merged**
