### PR TITLE
[Software] Update ref links/text labels

### PR DESCRIPTION
**Pull request by bact**
For the purpose of OMG/ISO standard doc preparation.

- gitoid
  - Point gitoid URLs to a specific commit
  - Update gitoid description in ContentIdentifierType and ExternalIdentifierType to match the updated terms
- Package URL
  - Point Package URL specification URLs to a specific commit
  - Update Package URL URLs to have both the core and the type definitions
  - **OR we like to point to this Annex instead?**: [https://spdx.github.io/spdx-spec/v3.0.1/annexes/pkg-url-specification/](https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/pkg-url-specification/)

### CODE REVIEW

**Review by goneall — CHANGES_REQUESTED** [review]
From the SPDX tech call on 30 July 2024:
- Update the gitoid URL's to include a release or commit (so that the content doesn't change over time)

**Comment by bact** [comment]
@goneall @zvr I have updated the GitHub URLs for Package URL and gitoid to point to a specific commit (latest):
- Package URL: [b33dda1](https://github.com/package-url/purl-spec/tree/b33dda1cf4515efa8eabbbe8e9b140950805f845)
- gitoid: [eb1ee5c](https://github.com/omnibor/spec/tree/eb1ee5c961c16215eb8709b2975d193a2007a35d)

--

Note that there are changes in gitoid-related terms:
- "OmniBOR Document" is now "Artifact Input Manifest"
- "OmniBOR Identifier" is now "Input Manifest Identifier"

The OmniBOR spec changelog is here:
- [Committed on Jun 21, 2023](https://github.com/omnibor/spec/commit/e7a7af2a94d98aecd921d9a65c51ab080f93e796#diff-32549ff8e6ff47e3685d98485a1bbd536d6dec7a8ce9e89dd20339a30cee4678L210)
  - "OmniBOR Document" --> "Input Manifest"
  - "OmniBOR Identifier" --> "Input Manifest Identifier"
- [Committed on Jul 26, 2023](https://github.com/omnibor/spec/commit/e81f9fb196c8816745f0de79fee79232b9ce3ba1)
  - "Input Manifest" --> "Artifact Input Manifest"

This PR already use the updated terms.

**Review by goneall — APPROVED** [review]
LGTM - Thanks @bact

**Comment by goneall** [comment]
@jeff-schutt - Can you review?

**Comment by bact** [comment]
[Software/Properties/packageUrl](https://github.com/spdx/spdx-3-model/blob/e1a2e54061482eda4b4ba571abf8ece1474b44c9/model/Software/Properties/packageUrl.md) made references to Package URL specification.

Currently, in this PR, it points to https://github.com/package-url/purl-spec/blob/b33dda1cf4515efa8eabbbe8e9b140950805f845/PURL-SPECIFICATION.rst

@zvr do you prefer to point it instead to https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/pkg-url-specification.md ?

**Comment by kestewart** [comment]
From the Omnibor Slack channel today
Andrew Lilley Brinker commented "For "OmniBOR Identifier" the term should actually be "Artifact Identifier", not "Input Manifest Identifier".    Can we adjust?

**Comment by bact** [comment]
Thank you @kestewart. I have changed the description as suggested, and then I changed it back. 

Comparing changes in the spec ([Apr 11, 2023](https://github.com/omnibor/spec/blob/63aeb4e034b0078fc8b90f91bd5002b5b4c67e17/spec/SPEC.md#omnibor-identifier), [Jun 21, 2023](https://github.com/omnibor/spec/blob/e7a7af2a94d98aecd921d9a65c51ab080f93e796/spec/SPEC-annex-A-filesystem-storage.md), [Jun 26, 2023](https://github.com/omnibor/spec/blob/e81f9fb196c8816745f0de79fee79232b9ce3ba1/spec/SPEC.md)), I believe "Input Manifest Identifier" is really a new name of "OmniBOR Identifier".

"OmniBOR Identifier" is also referred to as "OmniBOR Document Identifier".

Also, "Artifact Identifier" and "OmniBOR [Document] Identifier" are two distinct type of IDs, as we can see from these two code examples from Apr 11, 2023:

[Example 1](https://github.com/omnibor/spec/blob/63aeb4e034b0078fc8b90f91bd5002b5b4c67e17/spec/SPEC.md#omnibor-document-child-records):

> A child artifact which is itself a derived artifact would be represented by
> ```
> blob⎵${artifact id of child}⎵bom⎵${OmniBOR identifier of child's OmniBOR Document}\n
> ```

[Example 2](https://github.com/omnibor/spec/blob/63aeb4e034b0078fc8b90f91bd5002b5b4c67e17/spec/SPEC.md#omnibor-document-construction-by-a-build-tool):

> The build tool must persist a OmniBOR Document using the
`${artifact identifier}` and `${omnibor document identifier}` for each input.

This is my understanding of changes:

```text
[Old]
1)           Artifact Identifier  identifies  Artifact
2) OmniBOR [Document] Identifier  identifies  OmniBOR Document
                                   |
                                   v
[Current]
1)           Artifact Identifier  identifies  Artifact
2)     Input Manifest Identifier  identifies  Artifact Input Manifest
```

Artifact Input Manifest itself is also an Artifact.

A gitoid can represents both Input Manifest Identifier and Artifact Identifier.
The ambiguity and suggestion for differentiation are in the description of gitoid.

> - gitoid: [Gitoid](https://www.iana.org/assignments/uri-schemes/prov/gitoid), stands for [Git Object ID](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects). A gitoid of type blob is a unique hash of a binary artifact. A gitoid may represent either an [Artifact Identifier](https://github.com/omnibor/spec/blob/eb1ee5c961c16215eb8709b2975d193a2007a35d/spec/SPEC.md#artifact-identifier-types) for the software artifact or an [Input Manifest Identifier](https://github.com/omnibor/spec/blob/eb1ee5c961c16215eb8709b2975d193a2007a35d/spec/SPEC.md#input-manifest-identifier) for the software artifact's associated [Artifact Input Manifest](https://github.com/omnibor/spec/blob/eb1ee5c961c16215eb8709b2975d193a2007a35d/spec/SPEC.md#artifact-input-manifest); this ambiguity exists because the Artifact Input Manifest is itself an artifact, and the gitoid of that artifact is its valid identifier. Gitoids calculated on software artifacts (Snippet, File, or Package Elements) should be recorded in the SPDX 3.0 SoftwareArtifact's contentIdentifier property. Gitoids calculated on the Artifact Input Manifest (Input Manifest Identifier) should be recorded in the SPDX 3.0 Element's externalIdentifier property. See [OmniBOR Specification](https://github.com/omnibor/spec/), a minimalistic specification for describing software [Artifact Dependency Graphs](https://github.com/omnibor/spec/blob/eb1ee5c961c16215eb8709b2975d193a2007a35d/spec/SPEC.md#artifact-dependency-graph-adg).

I have adjusted the language of the description to make it easier to compare the difference between Input Manifest Identifier (formerly OmniBOR Identifier) and Artifact Identifier.

(If "OmniBOR Identifier" and "Artifact Identifier" are really the same in this context, I think it will be quite challenging to rewrite the description. As half of the existing description focuses on the difference between the two and how two different SPDX properties [contentIdentifier vs externalIdentifier] are intended to store their information.)

**Comment by bact** [comment]
> [Software/Properties/packageUrl](https://github.com/spdx/spdx-3-model/blob/e1a2e54061482eda4b4ba571abf8ece1474b44c9/model/Software/Properties/packageUrl.md) made references to Package URL specification.
> 
> Currently, in this PR, it points to https://github.com/package-url/purl-spec/blob/b33dda1cf4515efa8eabbbe8e9b140950805f845/PURL-SPECIFICATION.rst
> 
> @zvr do you prefer to point it instead to [https://spdx.github.io/spdx-spec/v3.0.1/annexes/pkg-url-specification/](https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/pkg-url-specification/)

From 2024-08-06 Tech meeting, we ageed to use the Annex E

**Review by kestewart — APPROVED** [review]
CHange matches discussion in the tech call.   Thanks.

**Review by zvr — COMMENTED** [review]
Merging this, since it has two approvals, and I'll return to update some stuff later.

**Pull request merged**
