### PR TITLE
Update RelationshipType.md to add in AI & Dataset useful relationships

### PR DESCRIPTION
**Pull request by kestewart**
Add in the relationships to summarize the training, testing and evidence to be used in AI and Dataset summarization.

Signed-off-by: Kate Stewart <kstewart@linuxfoundation.org>

### CODE REVIEW

**Comment by kestewart** [comment]
@rgopikrishnan91 - can you please review

**Review by goneall — APPROVED** [review]
LGTM - looks like useful relationship type additions.

**Comment by rgopikrishnan91** [comment]
I am not sure I understand what is evidenceFor?  But otherwise LGTM.

**Comment by rgopikrishnan91** [comment]
Discussed in the meeting. Looks good to me. It can be merged.!

**Comment by bennetkl** [comment]
Looks Good +1

**Pull request merged**
