### PR TITLE
Create safetyRiskAssessmentType.md

### PR DESCRIPTION
**Pull request by rgopikrishnan91**
Creating the property file for safetyRiskAssessmentType. @zvr @kestewart @lumjjb

### CODE REVIEW

**Review by kestewart — APPROVED** [review]
Looks good as a starting point. 

We may want to add in a link to the definitions of risk.

**Review by kestewart — APPROVED** [review]
Thanks for adding the link to the Article.

**Comment by bennetkl** [comment]
Confirmed link, and the explanation looks good.  One comment though, why is 's" in safety sometimes a 'capital' - only one occurrence, but I would have thought all should 'S'.

**Review by bennetkl — COMMENTED** [review]
Review the use or capital of safety and Safety for Range and correct if needed.  This is not a blocker

**Pull request merged**
