### PR TITLE
Change SBOMType to SbomType

### PR DESCRIPTION
**Pull request by davaya**
Use PascalCase for consistency with every other name in the model.

### CODE REVIEW

**Comment by armintaenzertng** [comment]
I agree with the change, I stumbled upon this a few times.
However, this has to be changed in `sbomType.md` and `Sbom.md`, too.

**Review by maxhbr — APPROVED** [review]
LGTM

**Review by goneall — CHANGES_REQUESTED** [review]
Based on [this comment](https://github.com/spdx/spdx-3-model/pull/405#issuecomment-1620237451), can you also update `sbomType.md` and `Sbom.md`?

**Review by goneall — APPROVED** [review]
Thanks @davaya

**Pull request merged**
