### PR TITLE
Update diagrams for v3.0.1

### LINKED ISSUE #1058: Check diagrams in "RDF model" chapter
Do the diagrams shown in https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/rdf-model/ reflect the v3.0.1 model?

- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/images/model-core-software.png
- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/images/model-ai.png 
- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/images/model-build.png
- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/images/model-dataset.png
- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/images/model-licensing.png
- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/images/model-security.png

### PR DESCRIPTION
**Pull request by bact**
### Changes

- Updated modified property names based on [CHANGELOG](https://github.com/spdx/spdx-3-model/blob/main/CHANGELOG.md)
  - Replace `contentType` -> `/Core/contentType`
  - Add `alder32`
  - Rename `parameters` -> `parameter`
  - Rename `imports` -> `import`
  - Rename `hasInputs` -> `hasInput`
  - Rename `hasOutputs` -> `hasOutput`
- Fix casing in types
- Fix casing in Classes in from->to relationship description
- Typo: `locationHint: anyUR` -> `locationHint: anyURI`
- Fix type: `DateTime`, from "String" to `xsd:dateTimeStamp`
- Add prefix `xsd:` to XML Schema Datatypes (xsd:string, xsd:decimal, xsd:boolean, xsd:positiveInteger, xsd:nonNegativeInteger)
- Sort enums
- Fix typo in VexAffectedVulnAssessmentRelationship/actionStatement type: Strting -> string
- Fix relevant typos in model descriptions (found during the diagram checks)
- Remove outdated model-security-profile.*

### Post-merge notes
- After this one is reviewed and merged, have to copy all relevant diagrams over to https://github.com/spdx/spdx-spec/tree/development/v3.0.1/docs/images -- see PR https://github.com/spdx/spdx-spec/pull/1077
- Recheck if they are displayed correctly with v3.0.1 labels on 
  - https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/rdf-model/ (during development)
  - https://spdx.github.io/spdx-spec/v3.0.1/annexes/rdf-model/
- Once everything is complete, close https://github.com/spdx/spdx-spec/issues/1058

### CODE REVIEW

**Comment by kestewart** [comment]
@bobmartin3000, @sbarnum - can you please review the diagrams before we merge.

**Review by kestewart — APPROVED** [review]
Cross checked the changes, and LGTM.

**Comment by sbarnum** [comment]
There are two issues that need fixed before merging this PR.

1. In the 'Pedigree' section within the RelationType enumeration in Core, the "copiedTo" and "expandsTo" values need swapped in order such that "copiedTo" is listed before "expandsTo"
2. The removal of Software/contentType from the model listed in the CHANGELOG is not reflected in the diagrams
     -   On the Software and the Core+Software tabs of the diagram the following changes need to be made for the "contentType" property on the File class
          -   Change "+ contentType: MediaType[0..1]" to "+ /Core/contentType: MediaType[0..1]"
               - an example of this can be seen in the "/SimpleLicensing/licenseText" property on the License class in the ExpandedLicensing namespace depicted in the Licensing tab of the diagrams
          - background color and property ordering changes (such as are seen in the AI and Dataset tabs of the diagrams are unnecessary in this case as those formatting approaches apply only to cardinality restrictions of superclasses
     -   New .png and .svg image files will need to be created and committed for the Software and the Core+Software tabs of the diagram

**Comment by bact** [comment]
Should `DateTime` a `xsd:dateTimeStamp` ?,
according to https://github.com/spdx/spdx-3-model/blob/main/model/Core/Datatypes/DateTime.md

Screenshot 2024-08-14 at 15 26 17

**Comment by zvr** [comment]
> Should DateTime a xsd:dateTimeStamp ?

I thought it had to be an `xsd:string` in order to have a `pattern` restricting it, but I was assured in discussion(s) that this will also work on any type, so we changed the model to have `xsd:dateTimeStamp` as superclass.

So yes, the diagram has to be fixed.

**Comment by bact** [comment]
> > Should DateTime a xsd:dateTimeStamp ?
> 
> I thought it had to be an `xsd:string` in order to have a `pattern` restricting it, but I was assured in discussion(s) that this will also work on any type, so we changed the model to have `xsd:dateTimeStamp` as superclass.
> 
> So yes, the diagram has to be fixed.

Thank you @zvr I will fix that then.

**Review by kestewart — APPROVED** [review]

**Comment by bact** [comment]
Currently the arrows pointing out from `ElementCollection` with labels "rootElement" and "element" have two heads, one points to `Element` and another to `SpdxDocument`. See the blue circle in the diagram below.

Screenshot 2024-08-15 at 04 50 23

Question 1 - which arrow the `*` in red circle supposed to be attached with? Left one or right one?

Question 2 - Does it possible to decoupled them to a diagram like this?

Screenshot 2024-08-15 at 05 01 15

**Comment by bact** [comment]
`Relationship` has two "subclass of" arrows point to `Element`.
Can we delete one of them?

Screenshot 2024-08-15 at 04 45 12

**Comment by goneall** [comment]
> Looks like `Relationship` has two "subclass of" arrows point to `Element`. Can we delete one of them?
> 
> Screenshot 2024-08-15 at 04 45 12

Yes - looks like it can be removed

**Comment by sbarnum** [comment]
I apologize for delayed response.
I have not been getting notifications of the continuing comments and changes here.

1) I do not object to the use of the specific XSD datatypes (e.g., xsd:string) here but do worry that this is a fairly broad and substantive change at this late date that brings with it non-insignificant risk. If we decide to do this we need to ensure that the textual spec explicitly specifies these types, that the generated TTL ontology files both import the XSD namespace and explicitly specify these types, that the JSON-LD context explicitly specifies these to their full expanded URI identifiers, and that ALL examples explicitly assert these types directly. If we cannot guarantee that all of this is done immediately then this change should not be made to the diagrams.
2) I agree with Alexios that if the spec now currently explicitly specifies xsd:dateTimeStamp then we should use it in the diagrams as well for the base type of the DateTime simple type.
3) Personally, I would recommend not decoupling both the 'element' and the 'rootElement' arrows (with their links to Element and their 'NOT' links to SpdxDocument) from 'ElementCollection'. I agree it is more legible when decoupled but would assert that it may make it actually more difficult for some readers to understand as "property" arrows from classes in these sorts of UML class diagrams (even though this is NOT technically a formal UML class diagram) are not typically duplicated to multiple different classes. I do not object strongly if everyone else feels strongly it should be decoupled and won't confuse readers but I would vote to keep them as they were.
4) I agree that the double subclassing arrows from Relationship to Element is an error and one should be removed. Not sure how that creeped in there. It looks like the current branch for this PR still has both arrows though.
5) I reviewed through this list of changes in the edited first comment for this PR and it looks like they are all implemented as described (including the two issues I called out in my previous comment).

**Comment by sbarnum** [comment]
Given my notification issues, if you need anything further from me to help get us across the 3.0.1 finish line please ping my cell (in my email sig).

**Comment by bact** [comment]
Thank you Sean. For very detailed comments. I will start to look at all of them now

**Comment by bact** [comment]
>     3. Personally, I would recommend not decoupling both the 'element' and the 'rootElement' arrows (with their links to Element and their 'NOT' links to SpdxDocument) from 'ElementCollection'. [...]

The two arrow groups got merged again.

>     4. I agree that the double subclassing arrows from Relationship to Element is an error and one should be removed. Not sure how that creeped in there. It looks like the current branch for this PR still has both arrows though.

Removed.

**Comment by bact** [comment]
@sbarnum new PNGs and SVGs are uploaded.

**Comment by kestewart** [comment]
ping @sbarnum - can you take another pass and confirm we're good to merge.

**Review by sbarnum — CHANGES_REQUESTED** [review]
The new model.drawio and related PNG & SVG files look good to me.

There remains one significant issue.

The 'images' folder in the branch to merge in this PR contains 2 files (model-security-profile.drawio and model-security-profile.png) that should NOT be present in the model. These appear to be an attempted duplication of the content in the model-security tab of the model.drawio diagram and its associated PNG and SVG images. They are both SIGNIFICANTLY out of date, incomplete, and incorrect. They should be removed.
Once that is done, this looks ready to merge.

**Comment by bact** [comment]
> The new model.drawio and related PNG & SVG files look good to me.
> 
> There remains one significant issue.
> 
> The 'images' folder in the branch to merge in this PR contains 2 files (model-security-profile.drawio and model-security-profile.png) that should NOT be present in the model. These appear to be an attempted duplication of the content in the model-security tab of the model.drawio diagram and its associated PNG and SVG images. They are both SIGNIFICANTLY out of date, incomplete, and incorrect. They should be removed. Once that is done, this looks ready to merge.

Thank you @sbarnum I will remove both files now.

**Comment by bact** [comment]
> The 'images' folder in the branch to merge in this PR contains 2 files (model-security-profile.drawio and model-security-profile.png) that should NOT be present in the model. These appear to be an attempted duplication of the content in the model-security tab of the model.drawio diagram and its associated PNG and SVG images. They are both SIGNIFICANTLY out of date, incomplete, and incorrect. They should be removed. Once that is done, this looks ready to merge.

@sbarnum Thank you. I have removed both files.

**Comment by bact** [comment]
Note: The PR to update the diagrams in spdx-spec repo to the most updated ones (from 22 Aug 2024) is at https://github.com/spdx/spdx-spec/pull/1077 (those are the files that will be displayed on our website at https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/rdf-model/ )

**Review by goneall — APPROVED** [review]
Based on tech call on 27 Aug 2024 - approved

**Comment by dcunited001** [comment]
@bact how did you generate the `model.drawio` file? i'm just curious because i've always found `drawio` to be a total PITA to script.

**Comment by bact** [comment]
I don't. I just used the draw.io webapp to draw and export

**Comment by dcunited001** [comment]
i see, thanks for letting me know! apologies for necroposting

**Pull request merged**
