### PR TITLE
Add `/Extension/` prefix to two `Extension` in diagram

### PR DESCRIPTION
**Pull request by bact**
- For labelling consistency
- Also add a space between a colon and a type
  - between "extension:" and "/Extension/"
  - between "useSensitivePersonalInformation:" and "/Core/PresenceType[0..1]"

### CODE REVIEW

**Comment by bact** [comment]
I'm actually not sure which one to choose between `/Extension/Extension` and `Extension`,
but we probably need to choose one and apply the same convention to all those four instances in the diagrams.

**Comment by kestewart** [comment]
@bact - given Sean's updates - is this still needed?

**Comment by bact** [comment]
I have checked the latest diagram - @kestewart we still need this.

**Comment by sbarnum** [comment]
This is fixed in #718

**Comment by bact** [comment]
Thank you

**Pull request closed without merging**
