### PR TITLE
fix some issues in markdowns in licensing branch

### PR DESCRIPTION
**Pull request by maxhbr**
There is a file missing in the licensing profile.

Ping @swinslow

### CODE REVIEW

**Comment by swinslow** [comment]
Thanks @maxhbr! Is there somewhere (in this repo, meeting minutes or elsewhere) where I can find a description of the format that things should be in for the spdx-3-model repo? And/or, is there a tool that is being used for checking validation?

**Comment by maxhbr** [comment]
I am currently hacking a tool to check validity and parse them. But that is not yet ready. After some tweaking I was able to parse it: https://github.com/maxhbr/spec-parser.hs/blob/26bb71b6f750fe6432af3bbd2df28192d5179888/puml/Model.svg

**Comment by maxhbr** [comment]
I also added some other small fixes

**Review by goneall — APPROVED** [review]
LGTM

**Review by kestewart — APPROVED** [review]
Changes look good.   We'll still need to get those TODOs filled in but no reason to block at this point.

**Pull request merged**
