### PR TITLE
json-ld context is currently invalid, add another check that validates the context for jsonld

### PR DESCRIPTION
**Pull request by maxhbr**
currently, the generated context.json file is not a valid context (at least the python library `rdflib` bails out). This adds a test to the pipeline to enforce its correctness. In the end this needs to be fixed in the spec parser.

## thrown error:
<pre>
$ python .github/workflows/test_context.py /path/to/context.json
Traceback (most recent call last):
  File "/tmp/tmp.gNYmijLEGg/spdx-3-model/.github/workflows/test_context.py", line 18, in <module>
    testLocalContext(sys.argv[1])
  File "/tmp/tmp.gNYmijLEGg/spdx-3-model/.github/workflows/test_context.py", line 13, in testLocalContext
    parseString(data)
  File "/tmp/tmp.gNYmijLEGg/spdx-3-model/.github/workflows/test_context.py", line 9, in parseString
    return Graph().parse(data=data, format='json-ld')
  File "/tmp/tmp.5ymDrNfyvh/venv/lib/python3.10/site-packages/rdflib/graph.py", line 1492, in parse
    parser.parse(source, self, **args)
  File "/tmp/tmp.5ymDrNfyvh/venv/lib/python3.10/site-packages/rdflib/plugins/parsers/jsonld.py", line 119, in parse
    to_rdf(data, conj_sink, base, context_data, version, generalized_rdf)
  File "/tmp/tmp.5ymDrNfyvh/venv/lib/python3.10/site-packages/rdflib/plugins/parsers/jsonld.py", line 138, in to_rdf
    return parser.parse(data, context, dataset)
  File "/tmp/tmp.5ymDrNfyvh/venv/lib/python3.10/site-packages/rdflib/plugins/parsers/jsonld.py", line 160, in parse
    context.load(local_context, context.base)
  File "/tmp/tmp.5ymDrNfyvh/venv/lib/python3.10/site-packages/rdflib/plugins/shared/jsonld/context.py", line 401, in load
    self._prep_sources(base, source, sources, referenced_contexts)
  File "/tmp/tmp.5ymDrNfyvh/venv/lib/python3.10/site-packages/rdflib/plugins/shared/jsonld/context.py", line 430, in _prep_sources
    new_ctx = self._fetch_context(
  File "/tmp/tmp.5ymDrNfyvh/venv/lib/python3.10/site-packages/rdflib/plugins/shared/jsonld/context.py", line 474, in _fetch_context
    raise INVALID_REMOTE_CONTEXT
<b>rdflib.plugins.shared.jsonld.errors.JSONLDException: invalid remote context</b>
</pre>

## btw.:
why is it a `.json` and not a `.json-ld` file?

### CODE REVIEW

**Comment by goneall** [comment]
Merge this after we fix the spec parser

**Comment by goneall** [comment]
@maxhbr will manually patch by adding `@context` to the context file.

**Comment by maxhbr** [comment]
This can be landed once https://github.com/spdx/spec-parser/pull/75 is merged

**Comment by maxhbr** [comment]
The CI is green and the merge of https://github.com/spdx/spec-parser/pull/75 has fixed the issue.

**Review by goneall — APPROVED** [review]
LGTM

**Pull request merged**
