### PR TITLE
Update CHANGELOG with changes since 2024-11-15

### PR DESCRIPTION
**Pull request by bact**
Update CHANGELOG with changes since 2024-11-15 that directly related to model semantics:

- #908
- #937 <s>(not merge yet)</s>
- #913 
- #935
- #941

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM - Thanks @bact

**Comment by goneall** [comment]
@zvr please review / merge

**Review by kestewart — APPROVED** [review]
Thanks for the detailed documentation.

**Comment by bact** [comment]
With two approvals, I will merge this.

**Pull request merged**
