### PR TITLE
Add ISO number to SWHID

### LINKED ISSUE #816: Add ISO number for SWHID
in Vocabulary / ExternalIdentifierType

### PR DESCRIPTION
**Pull request by bact**
Update reference to ISO 
SoftWare Hash IDentifier (SWHID) Specification V1.2 https://www.iso.org/standard/89985.html,
in ExternalIdentifierType and ContentIdentifierType

Use the ISO number without "DIS"

To fix #816

### CODE REVIEW

**Comment by goneall** [comment]
@zvr - we're going to go ahead and merge - if you disagree with the changes, feel free to open a new PR

**Comment by zvr** [comment]
Please *don't* !!!
I had assigned the issue to me, and I was working on it -- with all the other changes in the model.j
Generating merge conflicts costs a lot of time!

**Comment by goneall** [comment]
@zvr - can you join us briefly on a call to coordinate so we don't mess you up with other changes?  Zoom: https://zoom.us/j/99010789359

**Comment by zvr** [comment]
And it's not "ISO/IEC 18670", it's a DIS.

**Pull request merged**
