### PR TITLE
Change name of 'standard' property to be 'standardName'

### PR DESCRIPTION
**Pull request by sbarnum**
This PR implements the consensus decision of the Feb 06, 2024 Tech call to  address immediate concerns under Issue #387.

More structured approaches to fully resolving Issue #387 will be pursued post RC2.

### CODE REVIEW

**Review by goneall — APPROVED** [review]
I agree with the solution as well - and the PR LGTM.

Thanks @sbarnum and the participants on the tech team call.

**Review by goneall — CHANGES_REQUESTED** [review]
I just noticed that the CI is failing - there is a class referencing standard that also needs updating.  I believe it is `Artifact`.

@sbarnum - if you could add that change in as well.

**Comment by maxhbr** [comment]
this fails with `AssertionError: Property name standard does not match metadata standardName`

**Comment by maxhbr** [comment]
this also needs to be changed in:
- the title of the file
-  the places where it is used, e.g. in `.../Core/Classes/Artifact.md`
   - should the standard property in Artifact be using this?

**Comment by goneall** [comment]
@sbarnum @maxhbr - Let me know if you'd like me to update the PR with the required changes

**Comment by kestewart** [comment]
@goneall - discussed this in AI call, and we're good with it as is.   For future, Karen volunteers to coordinate with IEEE/ISO for future standard fields.

**Review by goneall — APPROVED** [review]
LGTM - CI failures are now fixed

**Review by kestewart — APPROVED** [review]
Thanks Gary for fixing the remaining refs.

**Pull request merged**
