### PR TITLE
run shacl2code in ci

### PR DESCRIPTION
**Pull request by maxhbr**
The script is from https://github.com/JPEWdev/shacl2code/blob/main/pyproject.toml

this should place the generated code in `./shacl2code` in gh-pages and attach it as an artifact to the ci run.

### CODE REVIEW

**Comment by goneall** [comment]
We probably should wait to merge this until after the other action PR's are resolved

**Comment by kestewart** [comment]
Need to get update from Jeff Licquia; before this one can move forward.

**Comment by kestewart** [comment]
@JPEWdev to review.

**Comment by maxhbr** [comment]
I think this is stale and outdated as there seems to be the decision to throw generated output into another repository.

**Comment by goneall** [comment]
Closing as it is now outdated

**Pull request closed without merging**
