### PR TITLE
Create modelDataPreprocessingSteps.md

### PR DESCRIPTION
**Pull request by rgopikrishnan91**
Create a properties file for dataPreprocessingSteps

### CODE REVIEW

**Comment by rgopikrishnan91** [comment]
@kestewart @zvr @lumjjb

**Review by kestewart — APPROVED** [review]
Looks good to me as a starting point.

**Review by bennetkl — COMMENTED** [review]
Typo change: remove one (Field captures Capture  ..).

**Comment by kestewart** [comment]
@rgopikrishnan91 - can you fix the typo that karen spotted please.

**Review by kestewart — CHANGES_REQUESTED** [review]
Fix typo "captures Capture"

**Comment by kestewart** [comment]
Discussed in call, overlap with Dataset profile, and clarified name to be model. 
Reviewed with Gopi, Karen & Kate on call.

**Review by kestewart — APPROVED** [review]
Fix typo "captures Capture"

**Pull request merged**
