### PR TITLE
Update RelationshipType.md

### PR DESCRIPTION
**Pull request by kestewart**
Indicate build* relationships should use LifecycleScopeType.  
Sort Build and Security/Vex type relationships into the alphabetical list.
Update definitions of build relationships.

Signed-off-by: Kate Stewart <kstewart@linuxfoundation.org>

### CODE REVIEW

**Review by puerco — APPROVED** [review]
/lgtm

**Review by maxhbr — APPROVED** [review]
LGTM

**Review by nishakm — CHANGES_REQUESTED** [review]
I think line 15 needs to be deleted. Other than that, LGTM.

**Comment by kestewart** [comment]
@nishakm - good catch.   Fixed.  Good to apply now?

**Review by nishakm — APPROVED** [review]

**Comment by nishakm** [comment]
@kestewart Thanks! OK to merge.

**Pull request merged**
