### PR TITLE
[WIP] AI: Rename energyConsumption to trainingEnergyConsumption (+suggested unit?)

### LINKED ISSUE #677: [3.0] AI: Rename: energyConsumption to trainingEnergyConsumption
From its description, the `energyConsumption` is intended for being a training energy consumption.

This is confirmed by a conversation here https://github.com/spdx/spdx-3-model/pull/671#discussion_r1535291356

The proposal is to rename `energyConsumption` to `trainingEnergyConsumption` to make it more explicit.

This is also to avoid conflict and make rooms for possible future properties like `inferenceEnergyConsumption` and `totalEnergyConsumption` (see #676).

### PR DESCRIPTION
**Pull request by bact**
- To fix #677 
  - See also Points (2)(d) and (2)(e) in Annex IXa Section 1 and Point (c) in Annex IXc in the [provisional agreement of the EU AI Act](https://www.europarl.europa.eu/meetdocs/2014_2019/plmrep/COMMITTEES/CJ40/AG/2024/02-13/1296003EN.pdf).
- Do we need a suggested unit of energy in the description?
  - For example,
    - Kilowatt-hour (kW-h) -- a non-SI unit, a common billing unit for electrical energy
    - Megajoule (MJ) -- a SI unit, 1 J is 1 Watt-second, 1 KW-h is 3.6 MJ.

### CODE REVIEW

**Comment by bact** [comment]
@bennetkl @rgopikrishnan91 please kindly review. Thank you

**Comment by bennetkl** [comment]
Yeah, I saw the suggestion to change Kilowatt-hour (kW-h) to Watts per minutes.  I wasn't at the meeting where this was discussed, but consideration that training time / energy is hug, I would think that minutes might be too small a unit, but will let Gopi add his comments, since I don't have a feel for why we wanted to change it.

**Comment by rgopikrishnan91** [comment]
I think KwH might be a better unit too. But is there a reason we can't allow it to be expressed in both ways and ask them to mention the unit? That way the ppl are not restricted and the parser is still happy? or much like date format we should pick one and stick to it. 

I understand the reason for using an SI unit, but I worry if we will be forcing ppl to do some conversions which might affect the uptake and hence my hesitation to pick a unit. 
@kestewart @bact @bennetkl

**Comment by bact** [comment]
Currently the filed is a string. So the maintainer can express it in anyway they like and just mention the unit.

In the description, we can ask them to mention the unit - and, if you have a preference/preferences, we can suggest that in the property description as well. Or we can just mention some common units with no preference as well.

And, yes, the Kw-H is much more common.

**Comment by bact** [comment]
There's also another way/unit to record the energy as well, to record the compute. See https://github.com/spdx/spdx-3-model/issues/676#issuecomment-2030949971

**Comment by rgopikrishnan91** [comment]
So two thoughts. 1. Inference energy consumption and 2. training energy consumption should be seperately noted?  I vote for giving a few options and specifying the format in which they should be specified. For example, allowed options could be (kwh, joules) and it should be mentioned as x.xx unit. (just a representative example, not a list of all the units we should consider

**Comment by kestewart** [comment]
Discussing this on the call, and agreement to make this a bit more future proof so evolving to have a Class - EnergyConsumption

{
  "energyConsumption": [
    {
      "type": "inference",
      "units": "kW/J",
      "quantity": 10
    },
    {
      "type": "learning",
      "units": "kW/J",
      "quantity": 5
    }
  ]
}

**Comment by bact** [comment]
I will close this PR. Please see instead these @rgopikrishnan91 PRs:
- #694
- #695
- #696
- #697

Summary:

AI team meeting 2024-04-03 agrees to change `energyConsumption` property range from `xsd:string` to a `EnergyConsumption` class. 

The `EnergyConsumption` class will have these properties: `trainingEnergyConsumption`, `finetuningEnergyConsumption`, `inferenceEnergyConsumption` - all with `EnergyConsumptionDescription` type.

`EnergyConsumptionDescription` will contains a unit information. The unit will have a type of`EnergyConsumptionDescriptionUnitType`.


More refs about compute and energy estimation are avail in #676

**Pull request closed without merging**
