### PR TITLE
Remove empty properties heading

### PR DESCRIPTION
**Pull request by goneall**
Fixes issue where the markdown parser is failing

### CODE REVIEW

**Review by kestewart — APPROVED** [review]
If this unbreaks the parser,  let's get it in.

**Comment by zvr** [comment]
Thanks, Gary. I had fixes all other instances of empty properties in the cleanup of #520, but of course this is new...

**Review by maxhbr — APPROVED** [review]
LGTM

**Comment by goneall** [comment]
> The CI is still broken for other reasons:

I just fixed the CI - it is now passing.

**Comment by goneall** [comment]
I'll go ahead and merge so we have a working CI

@puerco - sorry if this may cause a merge conflict with your work.

**Pull request merged**
