### PR TITLE
Doc: Add SHACL examples

### PR DESCRIPTION
**Pull request by zvr**
This adds examples of generated SHACL to represent the information of the model.

Discussed on the 2023-03-19 Tech call.

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM - I realize there are some related enhancements that may change the example, but I think we should go ahead and merge after one more review

**Review by sbarnum — CHANGES_REQUESTED** [review]
I think there are a few tweaks and simplifications needed before this PR is accepted and merged.

**Comment by goneall** [comment]
Let's move this to 3.1 to make sure the SHACL generated matches the documentation.  Any of the above suggested changes will not be a breaking change to the SHACL document itself.

**Comment by zvr** [comment]
So, this PR was about adding quick notes from the meeting we had about SHACL.

It seems we want better documentation, so I'll just close and abandon this.

I've opened #788 to document the need.

**Pull request closed without merging**
