### PR TITLE
Proposals of Lite-Profile

### PR DESCRIPTION
**Pull request by yoshi-i**
Due to my mis-operation (careless sync fork operation) of forked git repository, PR https://github.com/spdx/spdx-3-model/pull/350 contains other files for another PR.
I re-issue PR for Lite Profile with applying modification which pointed out in https://github.com/spdx/spdx-3-model/pull/350
Discussions for Lite Profile are held from May '23 time-frame and stored in  https://github.com/spdx/spdx-3-model/pull/350

Lite-Profile defines a profile that specializes in exchanging license information and meets the minimum elements of SBOM in the software supply chain for business practices. We believe it is effective for information exchange with legal departments of companies with limited knowledge of OSS in the supply chain, as it is valid as an SBOM.

### CODE REVIEW

**Comment by goneall** [comment]
I created a draft proposal for expressing the Lite profile using restrictions on the profile markdown file and a separate serialization markdown file in #523.  This is similar to what is discussed in issue #462.

**Comment by goneall** [comment]
@zvr - Could use your input on this and PR #523

**Comment by zvr** [comment]
I think #523 is the current one, following out new convention.

I have  question there whether it's complete, since it seems to be missing a couple of conditions, and I'm waiting for @yoshi-i to reply there.

**Comment by zvr** [comment]
Closing this, as #523 is the latest one.

**Pull request closed without merging**
