### PR TITLE
Change copyrightText to be xsd:string

### PR DESCRIPTION
**Pull request by goneall**
Removes the class hierarchy for expressing NONE and NOASSERTION for the copyrightText.  This simplifies the model.  The NONE and NOASSERTION values are already described in the copyrightText property description.  The text values can be parsed and interpreted as text.

### CODE REVIEW

**Comment by zvr** [comment]
My approach (outline in #297) was to have a `CopyrightText` class (inheriting from `xsd:string`) and two individuals, `NoneCopyrightText` and `NoAssertionCopyrightText`.

**Comment by zvr** [comment]
Yes, the individuals would have values "NONE" and "NOASSERTION" to make serialization a no-op.

**Review by kestewart — APPROVED** [review]

**Comment by kestewart** [comment]
Ok, given Steve's approved this, I'll merge it in now.   Thanks.

**Comment by swinslow** [comment]
+1 on these changes. I'm going to take a quick look through after merging this and see if anything else is needed.

@zvr Definitely interested in looking at #297 after RC / before actual 3.0.

**Pull request merged**
