### PR TITLE
Add spacing for better readability.

### PR DESCRIPTION
**Pull request by vargenau**

### CODE REVIEW

**Review by kestewart — APPROVED** [review]
Thanks!   Looks better this way.

**Review by goneall — APPROVED** [review]
LGTM

**Comment by goneall** [comment]
@vargenau - if you could resolve the merge conflicts, I can merge this in

**Comment by bact** [comment]
Already fixed by #723

The issue with one long paragraph in https://spdx.github.io/spdx-spec/v3.0/model/Core/Classes/NamespaceMap/ comes from the fact that it:

1. Use `1)` `2)` `3)` instead of `1.` `2.` `3.`
2. Indent is 3 spaces

This is already fixed in main. See [NamespaceMap.md](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/NamespaceMap.md)

Spacing issue in https://spdx.github.io/spdx-spec/v3.0/model/Core/Properties/dataLicense/ is also got fixed.
See [dataLicense](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/dataLicense.md)

**Comment by kestewart** [comment]
Ok, I took a pass at fixing the conflicts.   Hopefully it's ok.  If not, we'll do a new PR.  Merging this.

**Comment by bact** [comment]
Please see #760

**Pull request merged**
