### PR TITLE
Add licenseXml property to License and LicenseAddition

### LINKED ISSUE #359: Add a licenseXML field to the License class
Based on https://github.com/spdx/spdx-spec/issues/853, we should add the license XML to the listed license metadata.

We could also remove the license template field, but I would prefer to leave that in as a deprecated field for at last one release to allow migration to the new format.

### PR DESCRIPTION
**Pull request by goneall**
Resolves #359

### CODE REVIEW

**Review by kestewart — APPROVED** [review]
Looks good to me.

**Comment by goneall** [comment]
@swinslow - If you could do a quick review, I can merge if it looks OK

**Comment by swinslow** [comment]
@goneall My only question is whether the property on LicenseAddition should be called `additionXml` rather than `licenseXml`? To help clarify that it is not identical to a "license" XML file.

I'm not going to lose sleep over this one if you feel strongly that they should be the same  :)

**Comment by goneall** [comment]
> My only question is whether the property on LicenseAddition should be called additionXml rather than licenseXml? To help clarify that it is not identical to a "license" XML file.

@swinslow Your suggestion makes sense to me, however as I was starting to make the changes and reading the text of the licenseXml.md file, I notice it points to the [license XML fields](https://github.com/spdx/license-list-XML/blob/main/DOCS/xml-fields.md) which documents both the "license" and "exception" fields.

Since it is pointing to the same XML format for both license and addition, I'm wondering if they should keep the same term.  It does seem a bit odd to have something called licenseXml in the addition.  Let me know what you think. Should we leave it as is, change the name of the field to something more appropriate or change the documentation for license fields to define two different format?

**Comment by swinslow** [comment]
Yeah.... we refer to it generally as the "license list XML" -- I think we can keep it as `licenseXml` unless / until someone complains. I think it's fine. Thanks @goneall!

**Review by swinslow — APPROVED** [review]

**Pull request merged**
